### PR TITLE
added get_dev_reading_time to read the timestamp of a reading

### PR DESCRIPTION
**Pull request by logi85**
Hi, 

think this could be also nice for someone else.

### CODE REVIEW

**Comment by domschl** [comment]
Thanks for this! What do you think about returning a time value instead of a string?

**Comment by logi85** [comment]
You're welcome!

good idea,
I use the method this way, perhaps you want do add the strptime?:

def get_last_rssi(reading):
    rssi = fh.get_dev_reading_time("MAX_165836", "RSSI")
    return datetime.strptime(rssi, '%Y-%m-%d %H:%M:%S')

best regards
logi85

**Comment by domschl** [comment]
I've manually merged this into testing, will be part of the next version. Tx!

**Comment by domschl** [comment]
Now on pypi as fhem 0.5.0

**Pull request closed without merging**
